#!/bin/bash

source /var/www/html/.db.env

# VARIABLES
APP_DIR="/var/www/html"
BACKUP_DIR="$APP_DIR/db_backups"
DB_NAME="mydb"

DATE=$(date +"%Y-%m-%d")
BACKUP_FILE="$BACKUP_DIR/${DB_NAME}_$DATE.sql"

# CREATE MYSQL BACKUP
mysqldump -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" > "$BACKUP_FILE"

# EXIT IF BACKUP FAILED
if [ $? -ne 0 ]; then
  echo "MySQL backup failed"
  exit 1
fi

# GO TO APP DIRECTORY
cd "$APP_DIR" || exit 1

# GIT OPERATIONS
git add .
git commit -m "Daily DB backup: $DATE"
git push origin main
